USE SpotifyClone;

DELIMITER $$
CREATE TRIGGER trigger_usuario_delete
  BEFORE DELETE ON USERS
  FOR EACH ROW
BEGIN
  DELETE FROM FOLLOWING_ARTISTS
  WHERE user_id = OLD.user_id;
  DELETE FROM `HISTORY`
  WHERE user_id = OLD.user_id;
END $$

DELIMITER ;
